name = "logic-novel"
main = "worker.js"
compatibility_date = "2026-07-23"

# Kết nối D1 Database (Thay ID thực tế của bạn vào đây)
[[d1_databases]]
binding = "DB"
database_name = "logic_novel_db"
database_id = "f065b776-1b54-4327-8054-d723929894b1"
